import Layout from "@/components/Layout";
import { URL, capitalizedWords } from "@/components/Reuse";
import "@/styles/globals.css";
import "@/styles/login.css";
import Head from "next/head";
import { useRouter } from "next/router";
import { useCallback, useEffect, useState } from "react";
import { Provider } from "react-redux";
import store from "@/store";
import axios from "axios";

import Cookies from "js-cookie";

export default function App({ Component, pageProps }) {
  // const token = Cookies.get("jwt");

  // axios.interceptors.request.use(
  //   (config) => {
  //     config.headers.Authorization = `Bearer ${token}`;
  //     return config;
  //   },
  //   (error) => {
  //     return Promise.reject(error);
  //   }
  // );

  const router = useRouter();

  const [pageTitle, setPageTitle] = useState("Dashboard");

  useEffect(() => {
    const pathArray = router.pathname.split("/").filter(Boolean);
    const title =
      pathArray.length > 0 ? capitalizedWords(pathArray[0]) : "Dashboard";
    setPageTitle(title);
  }, [router.pathname]);

  useEffect(() => {
    document.title = `Swop Admin - ${pageTitle}`;
  }, [pageTitle]);

  // Global checking for user's authentication

  const isLoggedIn = useCallback(async () => {
    try {
      const response = await axios.get(`${URL}/api/v1/admin/isLoggedIn`, {
        withCredentials: true,
      });
    } catch (error) {
      router.push("/login");

      console.error(error);
    }
  }, []);

  useEffect(() => {
    isLoggedIn();
  }, [isLoggedIn]);

  return (
    <>
      {/*  */}
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Provider store={store}>
        {router.pathname.split("/")[1] === "login" ? (
          <Component {...pageProps} />
        ) : (
          <Layout>
            <Component {...pageProps} />
          </Layout>
        )}
      </Provider>
    </>
  );
}
